import { ScaledSheet } from 'react-native-size-matters';

const style = ScaledSheet.create({
  StudentDetail_main_container:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
    marginTop:'10@s',
    marginBottom:'10@s',
    marginHorizontal:'20@s',
  },
  first_section:{
    flex:1.3,
    alignContent:'center',
    alignItems:'center',
    width:'100%',
    // backgroundColor:'yellow'
  },
  first_section_name:{
    flex:1,
    alignItems:'center',
    marginTop:'20@s'
  },
  text:{
    fontWeight:'bold',
    fontSize:'18@s',
    marginTop:'10@s',
  },
  profile_image:{
    width: '100%', 
    height: '100%' ,
    borderRadius:'10@s',
    borderBottomLeftRadius:'30@s',
    borderBottomRightRadius:'30@s'
  },
  borderLine:{
    height:'0@s',
    width:'90%',
    borderColor:'gray',
    borderWidth:1,
    borderStyle:'solid',
  },
  second_section:{
    flex:1,
    flexDirection:'row',
    alignItems:'flex-start',
    width:'100%',
    paddingHorizontal:'20@s',
    marginTop:'10@s',
  },
  third_section:{
    flex:0.5,
    flexDirection:'row',
    alignItems:'center',
    width:'100%',
  },
  decline:{
    width:'140@s',
    height:'45@s',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor: '#E50202',
    borderRadius:'25@s',
  },
  button_class:{
    flex:1,
    borderColor:'gray',
    alignItems:'center'
  },
  profile_button:{
    alignItems:'center',
    fontSize:'20@s',
    fontWeight:'bold',
    color:'white'
  },
  approve:{
    width:'140@s',
    height:'45@s',
    justifyContent:'center',
    alignItems:'center',
    borderRadius:'25@s',
    backgroundColor:'#54E346'
  },
  Detail_row_title:{
    fontSize:'18@s',
    marginTop:'10@s',
  },
  Detail_row_value:{
    fontSize:'15@s',
    fontWeight:'bold'
  },
  Detail_row:{
   flex:1,
   flexDirection:'row',
   borderBottomWidth:'1@s',
   paddingBottom:'5@s',
   borderColor:'gray',
  },
});

export default style;