import { ScaledSheet } from 'react-native-size-matters';

const style = ScaledSheet.create({
  StudentDetail_main_container:{
    flex:1,
    marginTop:'10@s',
    marginBottom:'10@s',
    marginHorizontal:'10@s',
  },
  first_section:{
    flex:1,
    alignContent:'center',
    alignItems:'center',
    width:'100%',
    marginBottom:'10@s'
  },
  text:{
    fontWeight:'bold',
    fontSize:'18@s',
    marginTop:'10@s',
  },
  profile_image:{
    width: '100%', 
    height: 250 ,
    borderRadius:'10@s',
    borderBottomLeftRadius:'30@s',
    borderBottomRightRadius:'30@s'
  },
  second_section:{
    flexDirection:'row',
    alignItems:'flex-start',
    width:'100%',
    paddingHorizontal:'20@s',
    marginTop:'10@s',
  },
  third_section:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    width:'100%',
    paddingHorizontal:'10@s'
  },
  decline:{
    width:'140@s',
    height:'45@s',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor: '#E50202',
    borderRadius:'25@s',
  },
  profile_button:{
    alignItems:'center',
    fontSize:'20@s',
    fontWeight:'bold',
    color:'white'
  },
  approve:{
    width:'140@s',
    height:'45@s',
    justifyContent:'center',
    alignItems:'center',
    borderRadius:'25@s',
    backgroundColor:'#54E346'
  },
  Detail_row_title:{
    fontSize:'18@s',
    marginTop:'10@s',
  },
  Detail_row_value:{
    fontSize:'15@s',
    fontWeight:'bold'
  },
  Detail_row:{
   flex:1,
   flexDirection:'row',
   borderTopWidth:'1@s',
   paddingBottom:'5@s',
   borderColor:'gray',
  },
  receipt_image_section:{
    paddingHorizontal:'10@s',
  },
  receipt_image:{
    width:'100%',
    height:200,
    borderRadius:10
  }
});

export default style;